// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package events

import (
	"context"
	"github.com/diwise/iot-agent/internal/pkg/application/conversion"
	"sync"
)

// Ensure, that EventSenderMock does implement EventSender.
// If this is not the case, regenerate this file with moq.
var _ EventSender = &EventSenderMock{}

// EventSenderMock is a mock implementation of EventSender.
//
// 	func TestSomethingThatUsesEventSender(t *testing.T) {
//
// 		// make and configure a mocked EventSender
// 		mockedEventSender := &EventSenderMock{
// 			SendFunc: func(ctx context.Context, msg conversion.InternalMessage) error {
// 				panic("mock out the Send method")
// 			},
// 			StartFunc: func() error {
// 				panic("mock out the Start method")
// 			},
// 			StopFunc: func() error {
// 				panic("mock out the Stop method")
// 			},
// 		}
//
// 		// use mockedEventSender in code that requires EventSender
// 		// and then make assertions.
//
// 	}
type EventSenderMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, msg conversion.InternalMessage) error

	// StartFunc mocks the Start method.
	StartFunc func() error

	// StopFunc mocks the Stop method.
	StopFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg conversion.InternalMessage
		}
		// Start holds details about calls to the Start method.
		Start []struct {
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockSend  sync.RWMutex
	lockStart sync.RWMutex
	lockStop  sync.RWMutex
}

// Send calls SendFunc.
func (mock *EventSenderMock) Send(ctx context.Context, msg conversion.InternalMessage) error {
	if mock.SendFunc == nil {
		panic("EventSenderMock.SendFunc: method is nil but EventSender.Send was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg conversion.InternalMessage
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, msg)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//     len(mockedEventSender.SendCalls())
func (mock *EventSenderMock) SendCalls() []struct {
	Ctx context.Context
	Msg conversion.InternalMessage
} {
	var calls []struct {
		Ctx context.Context
		Msg conversion.InternalMessage
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *EventSenderMock) Start() error {
	if mock.StartFunc == nil {
		panic("EventSenderMock.StartFunc: method is nil but EventSender.Start was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc()
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedEventSender.StartCalls())
func (mock *EventSenderMock) StartCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *EventSenderMock) Stop() error {
	if mock.StopFunc == nil {
		panic("EventSenderMock.StopFunc: method is nil but EventSender.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//     len(mockedEventSender.StopCalls())
func (mock *EventSenderMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
